Task1/ToDo/models.py
from datetime import datetime
from ToDo import db, loginManager
from flask_login import UserMixin


@loginManager.user_loader
def load_user(userId):
    return User.query.get(int(userId))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password_hash = db.Column(db.String(60), nullable=False)
    tasks = db.relationship("Task", backref="author", lazy=True)

    def __repr__(self):
        return f"User ( {self.name}, {self.email}, {self.image} )"


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(255), nullable=False)
    content = db.Column(db.Text, nullable=False)
    completed = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    def __repr__(self):
        return f"Task ( {self.title}, {self.created_at} )"

Task1/ToDo/tasks/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField , SubmitField,BooleanField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired

class AddTaskForm(FlaskForm):
    title =StringField('Task', validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField('Add Task')
    complete = BooleanField('Completed')

class UpdateTaskForm(AddTaskForm):
    submit = SubmitField("Edit")

Task1/ToDo/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from ToDo.models import User

class RegistrationForm(FlaskForm):
    name = StringField("Username", validators=[DataRequired()])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=6)])
    confirm_password = PasswordField(
        "Confirm Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Sign Up")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("Email is already exists")




class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember = BooleanField("Remember Me")
    submit = SubmitField("Login")

Task1/ToDo/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
ToDoApp = Flask(__name__)
ToDoApp.config['SECRET_KEY'] = "hello from my secret key"
ToDoApp.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:anas204@localhost/ToDoListDB'



db = SQLAlchemy(ToDoApp)
bcrypt = Bcrypt(ToDoApp)
loginManager = LoginManager(ToDoApp)
loginManager.login_view = "users.login"
loginManager.login_message_category = "info"

# import users, blogs, main blueprints
from ToDo.main.routes import main
from ToDo.users.routes import users
from ToDo.tasks.routes import tasks

ToDoApp.register_blueprint(main)
ToDoApp.register_blueprint(users)
ToDoApp.register_blueprint(tasks)

Task1/ToDo/main/routes.py
from flask import render_template, Blueprint

main = Blueprint("main", __name__)

@main.route("/", methods=["GET"])
def index():
    return render_template("home.html", title="Home")

Task1/ToDo/tasks/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request, abort
from flask_login import current_user, login_required
from ToDo.tasks.forms import AddTaskForm, UpdateTaskForm

from ToDo.models import Task
from ToDo import db

tasks = Blueprint("tasks", __name__)

@tasks.route("/task/add", methods=["GET", "POST"])
@login_required
def addTask():
    form = AddTaskForm()
    if form.validate_on_submit():
        task = Task(
            title=form.title.data, content=form.content.data, user_id=current_user.id
        )
        db.session.add(task)
        db.session.commit()
        flash(f"Task added successfully", "success")
        return redirect(url_for("tasks.get_tasks"))
    return render_template("add_task.html", title="Add Task", form=form)


@tasks.route("/tasks", methods=["GET"])
@login_required
def get_tasks():
    tasks_res = current_user.tasks

    return render_template("tasks.html", title="Tasks", tasks=tasks_res)
@tasks.route("/task/<int:taskId>/update", methods=["GET", "POST"])
@login_required
def updateTask(taskId):
    form = UpdateTaskForm()
    task = Task.query.get_or_404(taskId)
    if task.author != current_user:
        abort(403)

    if request.method == "GET":
        form.title.data = task.title
        form.content.data = task.content

    if form.validate_on_submit():
        task.title = form.title.data
        task.content = form.content.data
        task.completed=form.complete.data
        db.session.commit()
        flash(f"Task updated successfully", "success")
        return redirect(url_for("tasks.get_tasks"))

    return render_template(
        "update_task.html", title="Update Task", task=task, form=form
    )


@tasks.route("/blog/<int:taskId>/delete", methods=["GET"])
def deleteTask(taskId):
    task = Task.query.get_or_404(taskId)
    if task.author != current_user:
        abort(403)
    db.session.delete(task)
    db.session.commit()
    flash(f"task {task.title} deleted successfully ", "success")
    return redirect(url_for("tasks.get_tasks"))

Task1/ToDo/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import login_user, current_user, logout_user
from ToDo.users.forms import RegistrationForm, LoginForm
from ToDo.models import User
from ToDo import bcrypt, db



users = Blueprint("users", __name__)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password_hash, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f"Welcome {user.username}", "success")
            return redirect(url_for("main.index"))
        else:
            flash(f"Invalid Credentials", "danger")
    return render_template("login.html", title="login", form=form)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password_hash.data).decode(
            "utf-8"
        )
        user = User(
            username=form.name.data,
            email=form.email.data,
            password_hash=hashed_password,
        )
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data}", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="register", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("users.login"))

Task1/ToDo/templates/add_task.html
{% extends 'base.html' %}
{% block body %}


<div class="card">
  <div class="card-header" >
      <div class="text-center mt-3">
        Add Task
      </div>
  </div>
  <div class="card-body">
      <form method="POST" >
         {{ form.hidden_tag() }}
          <div class="form-group">
              {{ form.title.label(class="form-control-label") }}
              {{ form.title(class="form-control form-control-lg") }}
              {% for error in form.title.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
          </div>
          <div class="form-group">
              {{ form.content.label(class="form-control-label") }}
              {{ form.content(class="form-control form-control-lg") }}
              {% for error in form.content.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
          </div>
          <div class="form-text">Add your task, Achiever!</div>

          {{form.complete(class="form-check-input")}}
          {{form.complete.label(class="form-check-label")}}
          <br>
          <br/>
          <div class="text-center mt-3">
            {{form.submit(class="btn btn-primary")}}
          </div>
      </form>
  </div>
</div>
{% endblock %}

Task1/ToDo/templates/base.html
<!doctype html>
<html lang="ar" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-dpuaG1suU0eT09tx5plTaGMLBsfDLzUCCUXOY2j/LSvXYuG6Bqs43ALlhIqAJVRb" crossorigin="anonymous">

    <title>{{title}}</title>
  </head>
  <body>
   {% include 'navbar.html' %}
  <br/>
   {% with messages = get_flashed_messages(with_categories=True)%}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}}  fade show" role="alert">
        {{message}}
    </div>
    {%endfor%}
    {%endif%}

    {% endwith %}
   </br>
  <div class="container">
      {% block body%}
      {% endblock %}
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    -->
  </body>

</html>

Task1/ToDo/templates/home.html
{% extends "base.html"%}
{% block body%}
<div class="home">
    <div class="row align-items-center">
        <div class="txt col-12 col-md-6 text-center">
            {% if current_user %}
            <h1 class="text-center text-primary"> Welcome {{current_user.name}} to ToDo  App </h1>
            {%else%}
            <h1 class="text-center text-primary"> Welcome to ToDo App </h1>
            {% endif %}
            <div class="">
                <p class=" text-muted"><i class="fa-solid fa-home"></i> Small steps every day lead to big achievements ,Let’s get things done!.
                </p>
                {% if not current_user%}
                <p>Please <button class="btn btn-primary">login</button> to access all features.</p>
                {%endif%}
            </div>
        </div>
        <div class="img col-12 col-md-6">
            <img src="{{ url_for('static', filename='images/intro.png') }}" width="100%" />
        </div>
    </div>
</div>

{% endblock %}

Task1/ToDo/templates/login.html
{% extends 'base.html' %}
{% block body %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Login</h3>
                </div>
                <div class="card-body">
                    <form method="POST" action="">
                        {{ form.hidden_tag()}}
                        <div class="mb-3">
                            {{form.email.label(class='form-label')}}
                            {{form.email(class='form-control')}}

                            {% if form.email.errors %}
                            {% for error in form.email.errors %}
                            <span class="text-danger d-block mb-1">{{error}}</span>
                            {% endfor %}
                            {%endif%}
                        </div>
                        <div class="mb-3">
                            {{form.password.label(class='form-label')}}
                            {{form.password(class='form-control')}}
                            {% if form.password.errors %}
                            {% for error in form.password.errors %}
                            <span class="text-danger d-block mb-1">{{error}}</span>
                            {% endfor %}
                            {%endif%}
                        </div>
                        <div class="mb-3">
                            {{form.remember(class='form-check-input')}}
                            {{form.remember.label(class='form-label')}}
                        </div>
                        <div class="mb-3 text-center">
                            {{form.submit(class='btn btn-primary')}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Task1/ToDo/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid d-flex align-items-center">
    <span class="navbar-brand mb-0 h1">To Do List</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav d-flex flex-row ms-3">
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.index')}}">Home</a>
        </li>
        {%if current_user.is_authenticated %}
           <li class="nav-item">
               <a class="nav-link" href="{{url_for('tasks.get_tasks')}}">My Tasks</a>
           </li>
        {%endif%}
      </ul>
      <div class="d-flex">
        {% if current_user.is_authenticated %}
        <div class="dropdown">
          <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton1"
                  data-bs-toggle="dropdown" aria-expanded="false">
                  My Account
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="{{url_for('tasks.addTask')}}">Add Task</a></li>
            <li><a class="dropdown-item" href="{{url_for('users.logout')}}">Logout</a></li>
          </ul>
        </div>
        {%else%}
        <a href="{{url_for('users.login')}}"><button class="btn btn-outline-primary me-1"> Login </button></a>
        <a href="{{url_for('users.register')}}"> <button class="btn btn-primary me-1"> Sign Up </button></a>
        {%endif%}

      </div>
    </div>
    </div>

</nav>

Task1/ToDo/templates/register.html
{% extends 'base.html' %}

{% block body %}
<div class="container mt-5 mb-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Register</h3>
                </div>
                <div class="card-body">
                    <form method="POST" action="">
                        {{ form.hidden_tag() }}
                        <div class="mb-3">
                            {{form.name.label(class='form-label')}}
                            {{form.name(class='form-control')}}
                            {% if form.name.errors %}
                            {% for error in form.name.errors%}
                            <span class="text-danger d-block">{{error}}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            {{form.email.label(class='form-label')}}
                            {{form.email(class='form-control')}}
                            {% if form.email.errors %}
                            {% for error in form.email.errors%}
                            <span class="text-danger d-block">{{error}}</span>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <div class="mb-3">
                            {{form.password.label(class='form-label')}}
                            {{form.password(class='form-control')}}
                            {% if form.password.errors %}
                            {% for error in form.password.errors%}
                            <span class="text-danger d-block">{{error}}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            {{form.confirm_password.label(class='form-label')}}
                            {{form.confirm_password(class='form-control')}}
                            {% if form.confirm_password.errors %}
                            {% for error in form.confirm_password.errors%}
                            <span class="text-danger d-block">{{error}}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <div class="mb-3 text-center">
                            {{form.submit(class='btn btn-primary')}}
                        </div>
                    </form>
                    <div class="text-center mt-3">
                        Already have an account? <a href="/login">Login here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Task1/ToDo/templates/tasks.html
{% extends 'base.html' %}
{% block body %}
<div class="card">
  <div class="card-header" >
      <div class="text-center mt-3">
        Tasks
      </div>
  </div>
  <div class="card-body">

        {% for task in tasks %}
      <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
            <div class="card-header">
            <h3>{{task.title}}</h3>

            </div>
          <div class="card-body">
              <p>{{task.content}}</p>
            {%if task.completed == True %}
                 <p class="text-success">Completed</p>
            {%else%}
                <p class="text-danger">Not Completed</p>
            {%endif%}
          </div>
          <div class="card-footer">
            <a class="btn btn-outline-primary" href="{{url_for('tasks.updateTask', taskId = task.id)}}">Edit</a>
            <a class="btn btn-outline-danger" href="{{url_for('tasks.deleteTask', taskId = task.id)}}">Delete</a>
        </div>
      </div>
        {% endfor %}

  </div>
</div>
{% endblock %}

Task1/ToDo/templates/update_task.html
{% extends 'base.html' %}
{% block body %}
<div class="add-blog">
    <div class="conteiner">
        <div class="card">
            <div class="card-header">Update Task</div>
            <div class="card-body">
                <form action="" method="post">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.title.label(class="form-control-label") }}
                        {{ form.title(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{ form.content.label(class="form-control-label") }}
                        {{ form.content(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{form.complete(class="form-check-input")}}
                        {{form.complete.label(class="form-check-label")}}
                    </div>
                    <div class="mt-3 text-center">
                        {{ form.submit(class="btn btn-outline-primary") }}
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
{%endblock%}